services:
  app:
    build: 
      context: .
    container_name: hacknio
    ports:
      - "${HOST_PORT:-3000}:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    command: npm run dev
    restart: unless-stopped

